name: UnitedStorage
version: 1.1.2
main: org.unitedlands.storage.UnitedStorage
api-version: 1.18
description: A custom United Lands plugin that lets you catch mobs.
author: Theriel_
depend: [ UnitedLib ]
softdepend: [ Towny ]
commands:
  storage:
    description: Player storage commands.
    aliases: [uls]
    permission: united.storage.player
  unitedstorage:
    description: UnitedStorage admin commands.
    aliases: [ulsa]
    permission: united.storage.admin
permissions:
  united.storage.player:
    default: true
  united.storage.admin:
    default: op